study/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/', include('app01.urls',namespace='app01')),

    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url, include

from web.views import account
from web.views import home
from web.views import project
from web.views import statistics
from web.views import wiki
from web.views import file
from web.views import setting
from web.views import issues
from web.views import dashboard

urlpatterns = [
    url(r'^register/$', account.register, name='register'),
    url(r'^login/sms$', account.login_sms,name='login_sms'),
    url(r'^login/$', account.login,name='login'),
    url(r'^image/code/$', account.image_code,name='image_code'),
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    url(r'^logout/$', account.logout, name='logout'),
    url(r'^index/$', home.index,name='index'),
    url(r'^price/$', home.price,name='price'),
    url(r'^payment/(?P<policy_id>\d+)/$', home.payment,name='payment'),
    url(r'^pay/$', home.pay,name='pay'),
    url(r'^pay/notify$', home.pay_notify,name='pay_notify'),

    # 项目列表
    url(r'^project/list/$', project.project_list,name='project_list'),
    # /project/star/my/1
    # /project/star/join/1
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star,name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar,name='project_unstar'),
    url(r'^manage/(?P<project_id>\d+)/',include([





        url(r'wiki$', wiki.wiki,name='wiki'),
        url(r'wiki/add/$', wiki.wiki_add,name='wiki_add'),
        url(r'wiki/catalog/$', wiki.wiki_catalog,name='wiki_catalog'),
        url(r'wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete,name='wiki_delete'),
        url(r'wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit,name='wiki_edit'),
        url(r'wiki/upload/$', wiki.wiki_upload,name='wiki_upload'),

        url(r'file/$', file.file, name='file'),
        url(r'file/delete/$', file.file_delete, name='file_delete'),
        url(r'cos/credential/$', file.cos_credential, name='cos_credential'),
        url(r'file/post/$', file.file_post, name='file_post'),
        url(r'file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        url(r'setting/$', setting.setting,name='setting'),
        url(r'setting/delete/$', setting.delete,name='setting_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/detail/(?P<issues_id>\d+)$', issues.issues_detail, name='issues_detail'),
        url(r'^issues/record/(?P<issues_id>\d+)$', issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)$', issues.issues_change, name='issues_change'),
        url(r'^issues/inviter/url/$', issues.invite_url, name='invite_url'),

        url(r'^dashboard/$', dashboard.dashboard,name='dashboard'),
        url(r'^dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),

        url(r'^statistics/$', statistics.statistics,name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority,name='statistics_priority'),
        url(r'^statistics/project/user/$', statistics.statistics_project_user,name='statistics_project_user'),
    ],None,None)),
    url(r'^inviter/join(?P<code>\w+)/$', issues.invite_join, name='invite_join'),

]
# 项目管理
"""
url(r'^manage/(?P<project_id>\d+)/dashboard$', project.project_star,name='project_star'),
url(r'^manage/(?P<project_id>\d+)/issues$', project.project_star,name='project_star'),
url(r'^manage/(?P<project_id>\d+)/statistics$', project.project_star,name='project_star'),
url(r'^manage/(?P<project_id>\d+)/file$', project.project_star,name='project_star'),
url(r'^manage/(?P<project_id>\d+)/wiki$', project.project_star,name='project_star'),
url(r'^manage/(?P<project_id>\d+)/setting$', project.project_star, name='project_star'),
"""

web/models.py
from django.db import models


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名',max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)

    #price_policy = models.ForeignKey(verbose_name='价格策略',to='PricePolicy',null=True,blank=True)

class PricePolicy(models.Model):
    """ 价格策略 """
    category_choices = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    )
    category = models.SmallIntegerField(verbose_name='收费类型', default=2, choices=category_choices)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')  # 正整数

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间', help_text='G')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小', help_text="M")

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class Transaction(models.Model):
    """ 交易记录 """
    status_choice = (
        (1, '未支付'),
        (2, '已支付')
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引

    user = models.ForeignKey(verbose_name='用户', to='UserInfo')
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy')

    count = models.IntegerField(verbose_name='数量（年）', help_text='0表示无限期')

    price = models.IntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class Project(models.Model):
    """ 项目表 """
    COLOR_CHOICES = (
        (1, "#56b8eb"),  # 56b8eb
        (2, "#f28033"),  # f28033
        (3, "#ebc656"),  # ebc656
        (4, "#a2d148"),  # a2d148
        (5, "#20BFA4"),  # #20BFA4
        (6, "#7461c2"),  # 7461c2,
        (7, "#20bfa3"),  # 20bfa3,
    )

    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)

    use_space = models.BigIntegerField(verbose_name='项目已使用空间', default=0, help_text='字节')

    star = models.BooleanField(verbose_name='星标', default=False)

    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    #
    bucket = models.CharField(verbose_name='cos桶', max_length=128)
    region = models.CharField(verbose_name='cos区域', max_length=32)
class ProjectUser(models.Model):
    """ 项目参与者 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    user = models.ForeignKey(verbose_name='参与者', to='UserInfo')
    star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)

class Wiki(models.Model):
    project = models.ForeignKey(verbose_name='项目',to='Project')
    title = models.CharField(verbose_name='标题',max_length=32)
    content = models.TextField(verbose_name='内容')
    depth = models.IntegerField(verbose_name='深度',default=1)
    # 自关联
    parent = models.ForeignKey(verbose_name='父文章',to="Wiki",null=True,blank=True,related_name='children')
    def __str__(self):
        return self.title

class FileRepository(models.Model):
    """ 文件库 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    file_type_choices = (
        (1, '文件'),
        (2, '文件夹')
    )
    file_type = models.SmallIntegerField(verbose_name='类型', choices=file_type_choices)
    name = models.CharField(verbose_name='文件夹名称', max_length=32, help_text="文件/文件夹名")
    key = models.CharField(verbose_name='文件储存在COS中的KEY', max_length=128, null=True, blank=True)

    # int类型最大表示的数据
    file_size = models.BigIntegerField(verbose_name='文件大小', null=True, blank=True, help_text='字节')

    file_path = models.CharField(verbose_name='文件路径', max_length=255, null=True,
                                 blank=True)  # https://桶.cos.ap-chengdu/....

    parent = models.ForeignKey(verbose_name='父级目录', to='self', related_name='child', null=True, blank=True)

    update_user = models.ForeignKey(verbose_name='最近更新者', to='UserInfo')
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)
class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType')
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """ 模块（里程碑）"""
    project = models.ForeignKey(verbose_name='项目', to='Project')
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """

    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project')

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """ 问题回复"""

    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复')
    )
    reply_type = models.IntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', to='Issues')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True)

class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_invite')

web/forms/file.py
from django import forms
from django.core.exceptions import ValidationError
from web.forms.bootstrap import BootStapForm
from web import models
from utils.tencent.cos import check_file
class FolderModelForm(BootStapForm,forms.ModelForm):
    class Meta:
        model = models.FileRepository
        fields = ['name']
    def __init__(self,request,parent_object,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request = request
        self.parent_object = parent_object

    def clean_name(self):
        name = self.cleaned_data['name']

        # 数据库判断 当前目录下此文件夹是否存在
        queryset = models.FileRepository.objects.filter(file_type=2, name=name, project=self.request.tracer.project)
        if self.parent_object:
            exists = queryset.filter(parent=self.parent_object).exists()
        else:
            exists = queryset.filter(parent__isnull=True).exists()
        if exists:
            raise ValidationError('文件夹已存在')
        return name


class FileModelForm(forms.ModelForm):
    etag = forms.CharField(label='ETag')
    class Meta:
        model = models.FileRepository
        exclude = ['project','file_type','update_user','update_datetime']
    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request = request
    def clean_file_path(self):
        return "https://{}".format(self.cleaned_data['file_path'])
    # """
    # def clean(self):
    #     key = self.cleaned_data['key']
    #     etag = self.cleaned_data['etag']
    #     size = self.cleaned_data['file_size']
    #     if not key or not etag:
    #         return self.cleaned_data
    #     # 向cos校验文件是否合法
    #     # sdk的功能
    #     from qcloud_cos.cos_exception import CosServiceError
    #     try:
    #         result = check_file(self.request.tracer.project.bucket,self.request.tracer.project.region,key
    #         )
    #     except CosServiceError as e:
    #         self.add_error(key,'文件不存在')
    #         return self.cleaned_data
    #     cos_etag = result.get('ETag')
    #     if etag != cos_etag:
    #         self.add_error('etag','ETag错误')
    #     cos_length = result.get('Content_Length')
    #     if int(cos_length) != size:
    #         self.add_error('size', '文件大小错误')
    #     return self.cleaned_data
    # """

web/views/dashboard.py
import collections
from django.shortcuts import render
from django.db.models import Count
from web import models
import datetime
import time
from django.http import JsonResponse
def dashboard(request,project_id):
    """ 概览 """
    # 问题数据处理
    status_dict = collections.OrderedDict()
    for key,text in models.Issues.status_choices:
        status_dict[key] = {'text':text,'count':0}
    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']
    # 项目成员
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id','user__username')
    # 最近的10个问题
    top_ten_object = models.Issues.objects.filter(project_id=project_id,assign__isnull=False).order_by('-id'[0:10])
    contex = {
        'status_dict':status_dict,
        'user_list':user_list,
        'top_ten_object':top_ten_object
    }
    return render(request,'dashboard.html',contex)

def issues_chart(request,project_id):
    """ 在概览页面上生成highcharts所需的数据 """
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0,30):
        date = today-datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple())*1000,0]

    result = models.Issues.objects.filter(project_id=project_id,create_datetime__gte=today-datetime.timedelta(days=30)).extra(
        select={'ctime':"strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))

    for item in result:
        date_dict[item["ctime"]][1] = item['ct']
    print(date_dict,222222222)
    print(list(date_dict.values()),3333333)
    return JsonResponse({'satus':True,'data':list(date_dict.values())})

web/views/setting.py
from django.shortcuts import render,HttpResponse,redirect
from utils.tencent.cos import delete_bucket
from web import models
def setting(request,project_id):
    return render(request,'setting.html')

def delete(request,project_id):
    """ 删除项目 """
    if request.method == "GET":
        return render(request, 'setting_delete.html')
    project_name = request.POST.get('project_name')
    if not project_name or project_name != request.tracer.project.name:
        return render(request, 'setting_delete.html',{'error':'项目名错误'})
    # 项目名写对了删除（只有创建者可以删除）
    if request.tracer.user != request.tracer.project.creator:
        return render(request, 'setting_delete.html', {'error': '只有项目创建者可删除项目'})

    # 1.删除桶
    #       -删除桶中的所有文件（找到桶中所有文件 + 删除文件）
    #       -删除桶中的所有文件碎片（找到桶中所有文件碎片 + 删除文件碎片）
    # 2.删除项目
    delete_bucket(request.tracer.project.bucket,request.tracer.project.region)
    models.Project.objects.filter(id=request.tracer.project.id).delete()
    return redirect("project_list")

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}首页{% endblock %}
{% block css %}
    <style>
    img{
        width:100%;
    }
    </style>
{% endblock %}
{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}">
        <img src="{% static 'img/index/index-2.png' %}">
        <img src="{% static 'img/index/index-3.png' %}">
        <img src="{% static 'img/index/index-4.png' %}">
    </div>

{% endblock %}

web/templates/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 加入成功 </h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}

    </div>

{% endblock %}

web/templates/login.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户登入{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
    .error-msg{
        color: red;
        position: absolute;
        font-size: 13px;
    }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户登入</div>
        <form  method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <img src="{% url 'image_code' %}" id="imageCode" title="点击更换图片">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right;">
                    <a href="{% url 'login_sms' %}">短信验证码登入？</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input type="submit" class="btn btn-primary" value="登  入"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script>
    $(function () {
        $('#imageCode').click(function () {
           var oldSrc = $(this).attr('src');
           $(this).attr('src',oldSrc+"?");

        })

    })
    </script>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户短信登入{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
    .error-msg{
        color: red;
        position: absolute;
        font-size: 13px;
    }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户短信登入</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right;">
                    <a href="{% url 'login' %}">用户名密码登入？</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登  入"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}



{% block js %}
    <script>
        //页面框架加载完成之后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickbtnSubmit();

        });
        /*
        点击登入
        */
        function bindClickbtnSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                //收集表单中的数据
                {#$('#regForm').serialize() //所有字段数据+ csrf_token#}
                //收集ajax发送到后台
                $.ajax({
                    url:"{% url 'login_sms' %}",
                    type:"POST",
                    data:$('#smsForm').serialize(),
                    dataType: "JSON",
                    success:function (res) {
                        if(res.status){
                            location.href =res.data
                        }else{
                            $.each(res.error,function (key,value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }

                    }
                })
            })

        }
        /*
        点击获取验证码的按钮绑定
         */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $('.error-msg').empty();
                //获取用户输入的手机号
                //找到输入框的ID，根据ID获取值
                var mobilePhone = $('#id_mobile_phone').val();
                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url:"{% url 'send_sms' %}", //等价于/send/sms/
                    type:'GET',
                    data:{mobile_phone:mobilePhone,tpl:"login"},
                    dataType: 'JSON',
                    success:function (res) {
                        //ajax请求发送成功之后，自动执行的函数
                        if(res.status){
                            sendSmsRemind();
                        }else{
                            //错误信息
                            console.log(res); //{status:False,error:{mobile_phone:["错误信息",]
                            $.each(res.error,function (key,value) {
                                $("#id_"+key).next().text(value[0]);

                            })
                        }

                    }
                })
            })
        }
        /*
        倒计时
         */
    function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }
    </script>
{% endblock %}

web/templates/payment.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %} 订单 {% endblock %}

{% block content %}

    <div class="container">
        <h2>订单信息（30分钟失效）</h2>
        <table class="table">
            <thead>
            <tr>
                <th>订单</th>
                <th>单价</th>
                <th>数量</th>
                <th>原价</th>
                <th>原订单抵扣</th>
                <th>实际支付</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ policy_object.title }}</td>
                <td>¥{{ policy_object.price }}</td>
                <td>{{ number }}</td>
                <td>¥{{ origin_price }}</td>
                <td>¥{{ balance }}</td>
                <td>¥{{ total_price }}</td>
            </tr>
            </tbody>
        </table>
        {% if transaction %}
            <div class="alert alert-warning">
                <div>原订单抵扣：¥{{ balance }}</div>
                <div style="margin-top: 10px">
                    原订单的时间为 {{ transaction.start_datetime }}
                    ~ {{ transaction.end_datetime }}，且实际支付¥{{ transaction.price }}
                </div>
            </div>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'pay' %}">立即支付</a>
    </div>

{% endblock %}

web/templates/price.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 套餐 {% endblock %}

{% block css %}
    <style>
        .slogan {
            font-size: 36px;
            text-align: center;
            margin: 50px 0;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="slogan">多种方案，使用多种场景</div>
        <div class="row">
            {% for item in policy_list %}
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="text-align: center;">{{ item.title }}</div>
                        <div class="panel-body">

                            <p style="text-align: center;font-size: 25px;">
                                ¥ {{ item.price }} / 年
                            </p>

                        </div>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <form class="form-inline" method="get" action="{% url 'payment' policy_id=item.id %}">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon">数量</div>
                                            <input type="number" name="number" value="1" class="form-control"
                                                   placeholder="购买数量">
                                            <div class="input-group-btn">
                                                <input type="submit" value="立即购买" class="btn btn-primary">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </li>
                            <li class="list-group-item">最大项目数量：{{ item.project_num }}</li>
                            <li class="list-group-item">最大项目空间：{{ item.project_space }}G</li>
                            <li class="list-group-item">最大文件支持：{{ item.per_file_size }}M</li>
                            <li class="list-group-item">项目成员：{{ item.project_member }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}